# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import myapp_pb2 as myapp__pb2


class myappStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.sayHello = channel.unary_unary(
        '/myapp.myapp/sayHello',
        request_serializer=myapp__pb2.queryRequest.SerializeToString,
        response_deserializer=myapp__pb2.queryResponse.FromString,
        )


class myappServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def sayHello(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_myappServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'sayHello': grpc.unary_unary_rpc_method_handler(
          servicer.sayHello,
          request_deserializer=myapp__pb2.queryRequest.FromString,
          response_serializer=myapp__pb2.queryResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'myapp.myapp', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
