# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: myapp.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='myapp.proto',
  package='myapp',
  syntax='proto2',
  serialized_pb=_b('\n\x0bmyapp.proto\x12\x05myapp\"#\n\x0cqueryRequest\x12\x13\n\x0bqueryString\x18\x01 \x02(\t\"/\n\rqueryResponse\x12\x1e\n\x07results\x18\x01 \x03(\x0b\x32\r.myapp.Result\")\n\x06Result\x12\r\n\x05query\x18\x02 \x02(\t\x12\x10\n\x08response\x18\x03 \x02(\t2@\n\x05myapp\x12\x37\n\x08sayHello\x12\x13.myapp.queryRequest\x1a\x14.myapp.queryResponse\"\x00\x42,\n\x16io.grpc.examples.myappB\nMyAppProtoP\x01\xa2\x02\x03HLW')
)




_QUERYREQUEST = _descriptor.Descriptor(
  name='queryRequest',
  full_name='myapp.queryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='queryString', full_name='myapp.queryRequest.queryString', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=57,
)


_QUERYRESPONSE = _descriptor.Descriptor(
  name='queryResponse',
  full_name='myapp.queryResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='results', full_name='myapp.queryResponse.results', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=106,
)


_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='myapp.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='query', full_name='myapp.Result.query', index=0,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='response', full_name='myapp.Result.response', index=1,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=149,
)

_QUERYRESPONSE.fields_by_name['results'].message_type = _RESULT
DESCRIPTOR.message_types_by_name['queryRequest'] = _QUERYREQUEST
DESCRIPTOR.message_types_by_name['queryResponse'] = _QUERYRESPONSE
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

queryRequest = _reflection.GeneratedProtocolMessageType('queryRequest', (_message.Message,), dict(
  DESCRIPTOR = _QUERYREQUEST,
  __module__ = 'myapp_pb2'
  # @@protoc_insertion_point(class_scope:myapp.queryRequest)
  ))
_sym_db.RegisterMessage(queryRequest)

queryResponse = _reflection.GeneratedProtocolMessageType('queryResponse', (_message.Message,), dict(
  DESCRIPTOR = _QUERYRESPONSE,
  __module__ = 'myapp_pb2'
  # @@protoc_insertion_point(class_scope:myapp.queryResponse)
  ))
_sym_db.RegisterMessage(queryResponse)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), dict(
  DESCRIPTOR = _RESULT,
  __module__ = 'myapp_pb2'
  # @@protoc_insertion_point(class_scope:myapp.Result)
  ))
_sym_db.RegisterMessage(Result)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\026io.grpc.examples.myappB\nMyAppProtoP\001\242\002\003HLW'))

_MYAPP = _descriptor.ServiceDescriptor(
  name='myapp',
  full_name='myapp.myapp',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=151,
  serialized_end=215,
  methods=[
  _descriptor.MethodDescriptor(
    name='sayHello',
    full_name='myapp.myapp.sayHello',
    index=0,
    containing_service=None,
    input_type=_QUERYREQUEST,
    output_type=_QUERYRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MYAPP)

DESCRIPTOR.services_by_name['myapp'] = _MYAPP

# @@protoc_insertion_point(module_scope)
